version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  nestjs-app:
    image: node:20-alpine
    container_name: nestjs-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/nestjs-database?authSource=admin
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
