name: ci
on: [pull_request]
defaults:
  run:
    working-directory: ./
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - id: dependencies
        run: npm install
      - name: List directories
        run: ls -l
      - name: Upload modules artifact
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: node_modules
  lint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Download modules artifact
        uses: actions/download-artifact@v4
        with:
          name: modules
      - name: Run lint
        run: npm run lint
  # tests:
  #   needs: prepare
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: ./github/workflows/prepare.yaml
  #     - name: Download prepare artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: prepare
  #     - name: Run tests
  #       run: npm run test:cov
  # tests_e2e:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download prepare artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: prepare
  #     - name: Run tests e2e
  #       run: npm run test:e2e
