name: ci
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20' 
      - name: Install dependencies
        run: npm install
  lint:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - name: Lint code
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - name: Run tests
        run: npm run test:cov
  tests_e2e:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - name: Run tests e2e
        run: npm run test:e2e